spring.application.name=resource
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/week13resource
spring.datasource.username=root
spring.datasource.password=Tsel@2020
spring.jpa.hibernate.ddl-auto=update
server.port=8082

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.security=DEBUG
logging.level.com.assignment2.resource.security=DEBUG

jwt.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxC+09HPuTFZCbmCa4LxcA00mPsrAxabQU+KGkvtprh1WTQffyGXqHsQ9/Xm5HXlhw3hLTmRWGqIb+dQbD4C3FFsVRyp8Q0GqsCl3SV5AvPcJpND332arV8scjfsaaaz3wNZ2Vwc34L1OSGIWZJB5+6aakEpot9qHIADSGHG0ZfX0wdfPWN9Ru6lRkcFhwo1m/Rt6rDJhZNHyFYRBC8o+GKJs5gClhIXxViYZp0nqpbFb8wUT6N/4j2LQqpW89B6/3vWF6VQW0INwIjA/w9KEU88CcY1aZaTqdiCHlDKTyrYVbj7KlwiS7a5DJD8EsMzyJTCad6MxZCmiKFz3NZGidQIDAQAB

server.error.include-binding-errors=always
server.error.include-message=always