sonar.projectKey=Spring-Demo
sonar.projectName=midtest
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.login=sqa_78d9d4824e229dea10af39f8e30733bcfb10006d
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.java.coveragePlugin=jacoco
sonar.dynamicAnalysis=reuseReports
sonar.jacoco.reportPath=${project.basedir}/target/jacoco.exec
sonar.language=java
sonar.sourceEncoding=UTF-8
