server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: customer_service
          uri: http://localhost:8082
          predicates:
            - Path=/customers/**
          filters:
            - name: ApiKeyFilter
              args:
                apiKeyHeaderName: api-key
                authServiceUrl: http://localhost:8083/auth-api-key/validate
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
          filters:
            - name: ApiKeyFilter
              args:
                apiKeyHeaderName: api-key
                authServiceUrl: http://localhost:8083/auth-api-key/validate
