spring.application.name=assignment3

primary.datasource.url=jdbc:mysql://localhost:3306/fptweek4
primary.datasource.username=root
primary.datasource.password=Tsel@2020
primary.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

secondary.datasource.url=jdbc:mysql://localhost:3306/fptweek4part2
secondary.datasource.username=root
secondary.datasource.password=Tsel@2020
secondary.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
